//var nombre =prompt("ingrese su nombre ");
//alert("hola "+nombre+" ,Bienvenido");

//var num1=prompt("ingrese un numero 1");
//var num2=prompt("ingrese un numero 2");

// num1=parseInt(num1)
// num2=parseInt(num2)

// //alert("la suma es: "+(num1+num2));
// if(num1>num2){
//     alert("el numero 1 es mayor");

// }else if (num1==num2){
//     alert("son iguiales");
// }
// else{
//     alert("El numero 2 es mayor");

// }
// var Nombreusuario=prompt("hola usuario,¿ Como te llamas ?")

// switch(Nombreusuario){
// case "fabian":
// alert("hola fabian Yo te conosco!!") ;
// break;
// default :
//     alert("hola Yo no  te conosco!!") ;
    

// }

